### PR TITLE
Update PluginConfig.cs - Fix null reference

### LINKED ISSUE #27: Bug Report - Not working on 2.47
**Describe the bug**
Not working on Keepass 2.47 portable gives a compatibility worning on starting Keepass. 4.0.3beta is unzipped in Plugins subfolder of Keepass portable folder

### LINKED ISSUE #29: Bug Report - 4.0.4beta
**Describe the bug**
Version 4.0.4beta is not working on KeePass 2.47. I've already cleaned up the plugin cache folder and still getting the warning message.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clean up the old plugin and plugin cache files.
2. Copy the latest plugin into "Plugins" folder
3. Start KeePass

**Screenshots**

System Info:
 - OS: Windows 10 Version 2004
 - .NET Framework 4.8.04084
 - KeePass v2.47
 
 Is anyone get the same problem?

### PR DESCRIPTION
**Pull request by Rookiestyle**
Fixes #29

Method `UpdateConfig` dumps because of `configVer = new Version(ConfigVersion);`
ConfigVersion is null, if GoogleSync.ConfigVersion can be read in method `InitLegacyDefault`

### CODE REVIEW

File: src/PluginConfig.cs [hunk 1]
```diff
@@ -454,8 +454,8 @@ static PluginConfig InitLegacyDefault(IPluginHost host)
 			if (!Version.TryParse(verString, out configVersion))
 			{
 				configVersion = new Version(Ver0);
-				update.ConfigVersion = Ver0;
 			}
+			update.ConfigVersion = configVersion;
```
Comment (walterpg) [inline src/PluginConfig.cs:458]: This doesn't compile, try:
`
			update.ConfigVersion = configVersion.ToString(2);
`

**Review by walterpg — CHANGES_REQUESTED** [review]
Ouch.  Thanks for finding this.

I doubt this has anything to do with #27 though, since this is new code in 4.0.4-beta.

**Comment by Rookiestyle** [comment]
My bad, it's reworked now and I also removed the link to #27

**Review by walterpg — APPROVED** [review]
That was quick! Thanks.
